#docker version
version: '3.8'
services:
  #env for the php with apache
  php-apache-environment:
    container_name: php-apache
    image: php:8.0-apache
    volumes:
      - ./src:/var/www/html/
    ports:
      - 8000:80
  #env for the MySQL
  db:
    container_name: db
    image: mysql
    restart: always
    environment:
        MYSQL_ROOT_PASSWORD: MYSQL_ROOT_PASSWORD
        MYSQL_DATABASE: MY_DATABASE
        MYSQL_USER: MYSQL_USER
        MYSQL_PASSWORD: MYSQL_PASSWORD
    ports:
        - "9906:3306"
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
        - '8080:80'
    restart: always
    environment:
        PMA_HOST: db
    depends_on:
        - db
